/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "ISafeMint",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISafeMint__factory>;
    getContractFactory(
      name: "SafeMint",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeMint__factory>;
    getContractFactory(
      name: "SafeMintData",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeMintData__factory>;

    getContractAt(
      name: "AccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "ISafeMint",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISafeMint>;
    getContractAt(
      name: "SafeMint",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeMint>;
    getContractAt(
      name: "SafeMintData",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeMintData>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
