/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SafeMintInterface extends ethers.utils.Interface {
  functions: {
    "AUDITOR_ROLE()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "adminSetProjectPrice(uint256)": FunctionFragment;
    "adminWithdraw(address)": FunctionFragment;
    "auditorClaimFee(string)": FunctionFragment;
    "challengeArr(uint256)": FunctionFragment;
    "contractAddress(address)": FunctionFragment;
    "editProject(string,uint256,uint256,string)": FunctionFragment;
    "getChallenge(uint256,uint256)": FunctionFragment;
    "getLocked(uint256,uint256)": FunctionFragment;
    "getPassed(uint256,uint256)": FunctionFragment;
    "getPending(uint256,uint256)": FunctionFragment;
    "getProject(string)": FunctionFragment;
    "getProjectById(uint256)": FunctionFragment;
    "getReject(uint256,uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getRoleMember(bytes32,uint256)": FunctionFragment;
    "getRoleMemberCount(bytes32)": FunctionFragment;
    "getRoleMemberIndex(bytes32,address)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "lockedArr(uint256)": FunctionFragment;
    "namehashToId(bytes32)": FunctionFragment;
    "passedArr(uint256)": FunctionFragment;
    "pendingArr(uint256)": FunctionFragment;
    "projectArr(uint256)": FunctionFragment;
    "projectId(string)": FunctionFragment;
    "projectName(string)": FunctionFragment;
    "projectPrice()": FunctionFragment;
    "projectStatus(string,uint8)": FunctionFragment;
    "rejectArr(uint256)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "saveProject(string,address,uint256,uint256,string)": FunctionFragment;
    "token()": FunctionFragment;
    "user(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminSetProjectPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdraw",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "auditorClaimFee",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "editProject",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getChallenge",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLocked",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPassed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPending",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getProject", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getProjectById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReject",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMember",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberIndex",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "namehashToId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "passedArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "projectId", values: [string]): string;
  encodeFunctionData(functionFragment: "projectName", values: [string]): string;
  encodeFunctionData(
    functionFragment: "projectPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projectStatus",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "saveProject",
    values: [string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(functionFragment: "user", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminSetProjectPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auditorClaimFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeArr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "editProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLocked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPassed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPending", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProjectById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockedArr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "namehashToId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "passedArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "projectArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "projectId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rejectArr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "saveProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "user", data: BytesLike): Result;

  events: {
    "AuditorClaimFee(string,uint256)": EventFragment;
    "EditProject(string,uint256,uint256,string)": EventFragment;
    "ProjectStatus(string,uint8)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "SaveProject(string,address,address,uint256,uint256,string,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuditorClaimFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EditProject"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProjectStatus"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SaveProject"): EventFragment;
}

export type AuditorClaimFeeEvent = TypedEvent<
  [string, BigNumber] & { name: string; projectFee: BigNumber }
>;

export type EditProjectEvent = TypedEvent<
  [string, BigNumber, BigNumber, string] & {
    name: string;
    startTime: BigNumber;
    endTime: BigNumber;
    ipfsAddress: string;
  }
>;

export type ProjectStatusEvent = TypedEvent<
  [string, number] & { name: string; status: number }
>;

export type RoleGrantedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type RoleRevokedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type SaveProjectEvent = TypedEvent<
  [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    BigNumber
  ] & {
    name: string;
    owner: string;
    projectContract: string;
    startTime: BigNumber;
    endTime: BigNumber;
    ipfsAddress: string;
    projectPrice: BigNumber;
    projectId: BigNumber;
  }
>;

export class SafeMint extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SafeMintInterface;

  functions: {
    AUDITOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    adminSetProjectPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    adminWithdraw(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    auditorClaimFee(
      name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    contractAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    editProject(
      name: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getChallenge(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        })[]
      ]
    >;

    getLocked(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        })[]
      ]
    >;

    getPassed(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        })[]
      ]
    >;

    getPending(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        })[]
      ]
    >;

    getProject(
      name: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        [
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        }
      ]
    >;

    getProjectById(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        }
      ]
    >;

    getReject(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        })[]
      ]
    >;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRoleMemberIndex(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    namehashToId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      }
    >;

    projectId(name: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    projectName(name: string, overrides?: CallOverrides): Promise<[boolean]>;

    projectPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    projectStatus(
      name: string,
      status: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    saveProject(
      name: string,
      projectContract: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    token(overrides?: CallOverrides): Promise<[string]>;

    user(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  AUDITOR_ROLE(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  adminSetProjectPrice(
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  adminWithdraw(
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  auditorClaimFee(
    name: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  challengeArr(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  contractAddress(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  editProject(
    name: string,
    startTime: BigNumberish,
    endTime: BigNumberish,
    ipfsAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getChallenge(
    start: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    })[]
  >;

  getLocked(
    start: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    })[]
  >;

  getPassed(
    start: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    })[]
  >;

  getPending(
    start: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    })[]
  >;

  getProject(
    name: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      [
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      }
    ]
  >;

  getProjectById(
    _projectId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    }
  >;

  getReject(
    start: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    })[]
  >;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  getRoleMember(
    role: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleMemberCount(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRoleMemberIndex(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  lockedArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  namehashToId(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  passedArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  pendingArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  projectArr(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    }
  >;

  projectId(name: string, overrides?: CallOverrides): Promise<BigNumber>;

  projectName(name: string, overrides?: CallOverrides): Promise<boolean>;

  projectPrice(overrides?: CallOverrides): Promise<BigNumber>;

  projectStatus(
    name: string,
    status: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rejectArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  saveProject(
    name: string,
    projectContract: string,
    startTime: BigNumberish,
    endTime: BigNumberish,
    ipfsAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  token(overrides?: CallOverrides): Promise<string>;

  user(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    AUDITOR_ROLE(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    adminSetProjectPrice(
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    adminWithdraw(to: string, overrides?: CallOverrides): Promise<void>;

    auditorClaimFee(name: string, overrides?: CallOverrides): Promise<void>;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractAddress(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    editProject(
      name: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getChallenge(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      })[]
    >;

    getLocked(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      })[]
    >;

    getPassed(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      })[]
    >;

    getPending(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      })[]
    >;

    getProject(
      name: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        [
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        }
      ]
    >;

    getProjectById(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      }
    >;

    getReject(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      })[]
    >;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMemberIndex(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    namehashToId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      }
    >;

    projectId(name: string, overrides?: CallOverrides): Promise<BigNumber>;

    projectName(name: string, overrides?: CallOverrides): Promise<boolean>;

    projectPrice(overrides?: CallOverrides): Promise<BigNumber>;

    projectStatus(
      name: string,
      status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    saveProject(
      name: string,
      projectContract: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;

    user(arg0: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "AuditorClaimFee(string,uint256)"(
      name?: string | null,
      projectFee?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { name: string; projectFee: BigNumber }
    >;

    AuditorClaimFee(
      name?: string | null,
      projectFee?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { name: string; projectFee: BigNumber }
    >;

    "EditProject(string,uint256,uint256,string)"(
      name?: string | null,
      startTime?: null,
      endTime?: null,
      ipfsAddress?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, string],
      {
        name: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
      }
    >;

    EditProject(
      name?: string | null,
      startTime?: null,
      endTime?: null,
      ipfsAddress?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, string],
      {
        name: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
      }
    >;

    "ProjectStatus(string,uint8)"(
      name?: string | null,
      status?: null
    ): TypedEventFilter<[string, number], { name: string; status: number }>;

    ProjectStatus(
      name?: string | null,
      status?: null
    ): TypedEventFilter<[string, number], { name: string; status: number }>;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "SaveProject(string,address,address,uint256,uint256,string,uint256,uint256)"(
      name?: string | null,
      owner?: string | null,
      projectContract?: string | null,
      startTime?: null,
      endTime?: null,
      ipfsAddress?: null,
      projectPrice?: null,
      projectId?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber
      ],
      {
        name: string;
        owner: string;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectPrice: BigNumber;
        projectId: BigNumber;
      }
    >;

    SaveProject(
      name?: string | null,
      owner?: string | null,
      projectContract?: string | null,
      startTime?: null,
      endTime?: null,
      ipfsAddress?: null,
      projectPrice?: null,
      projectId?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber
      ],
      {
        name: string;
        owner: string;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectPrice: BigNumber;
        projectId: BigNumber;
      }
    >;
  };

  estimateGas: {
    AUDITOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    adminSetProjectPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    adminWithdraw(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    auditorClaimFee(
      name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    editProject(
      name: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getChallenge(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLocked(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPassed(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPending(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProject(name: string, overrides?: CallOverrides): Promise<BigNumber>;

    getProjectById(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReject(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMemberIndex(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    namehashToId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectId(name: string, overrides?: CallOverrides): Promise<BigNumber>;

    projectName(name: string, overrides?: CallOverrides): Promise<BigNumber>;

    projectPrice(overrides?: CallOverrides): Promise<BigNumber>;

    projectStatus(
      name: string,
      status: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    saveProject(
      name: string,
      projectContract: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    user(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    AUDITOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    adminSetProjectPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    adminWithdraw(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    auditorClaimFee(
      name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    editProject(
      name: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getChallenge(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLocked(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPassed(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPending(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProject(
      name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProjectById(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReject(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMemberIndex(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    namehashToId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectId(
      name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectName(
      name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    projectStatus(
      name: string,
      status: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    saveProject(
      name: string,
      projectContract: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    user(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
