/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SafeMintInterface extends ethers.utils.Interface {
  functions: {
    "ARBITRATOR_ROLE()": FunctionFragment;
    "AUDITOR_ROLE()": FunctionFragment;
    "Arbitrate(string,uint8)": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "adminSetAuditPrice(uint256)": FunctionFragment;
    "adminSetChellengePrice(uint256)": FunctionFragment;
    "adminSetDuration(uint256)": FunctionFragment;
    "adminSetProjectPrice(uint256)": FunctionFragment;
    "adminWithdraw(address)": FunctionFragment;
    "audit(string,string,uint8)": FunctionFragment;
    "auditPrice()": FunctionFragment;
    "auditRecord(uint256,uint256)": FunctionFragment;
    "challenge(string,string)": FunctionFragment;
    "challengeArr(uint256)": FunctionFragment;
    "challengePrice()": FunctionFragment;
    "challengeRecord(uint256,uint256)": FunctionFragment;
    "claimAuditReward(uint256)": FunctionFragment;
    "claimChellengeReward(uint256)": FunctionFragment;
    "contractAddress(address)": FunctionFragment;
    "duration()": FunctionFragment;
    "editProject(string,uint256,uint256,string)": FunctionFragment;
    "feeRecord(uint256)": FunctionFragment;
    "getChallenge(uint256,uint256)": FunctionFragment;
    "getLocked(uint256,uint256)": FunctionFragment;
    "getPassed(uint256,uint256)": FunctionFragment;
    "getPending(uint256,uint256)": FunctionFragment;
    "getReject(uint256,uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getRoleMember(bytes32,uint256)": FunctionFragment;
    "getRoleMemberCount(bytes32)": FunctionFragment;
    "getRoleMemberIndex(bytes32,address)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "lockedArr(uint256)": FunctionFragment;
    "passedArr(uint256)": FunctionFragment;
    "pendingArr(uint256)": FunctionFragment;
    "projectArr(uint256)": FunctionFragment;
    "projectId(bytes32)": FunctionFragment;
    "projectName(string)": FunctionFragment;
    "projectPrice()": FunctionFragment;
    "rejectArr(uint256)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "saveProject(string,address,uint256,uint256,string)": FunctionFragment;
    "user(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ARBITRATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "Arbitrate",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminSetAuditPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminSetChellengePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminSetDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminSetProjectPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdraw",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "audit",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "auditPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auditRecord",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challenge",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challengePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challengeRecord",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAuditReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimChellengeReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "duration", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "editProject",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChallenge",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLocked",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPassed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPending",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReject",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMember",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberIndex",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "passedArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "projectName", values: [string]): string;
  encodeFunctionData(
    functionFragment: "projectPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rejectArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "saveProject",
    values: [string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "user", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "ARBITRATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Arbitrate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminSetAuditPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminSetChellengePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminSetDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminSetProjectPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "audit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "auditPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "auditRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "challenge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "challengeArr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAuditReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimChellengeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "duration", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "editProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLocked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPassed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPending", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getReject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockedArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "passedArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "projectArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "projectId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rejectArr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "saveProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "user", data: BytesLike): Result;

  events: {
    "ArbitrateProject(string,address,uint8)": EventFragment;
    "AuditProject(string,address,uint256,string,uint8)": EventFragment;
    "ChallengeProject(string,address,uint256,string)": EventFragment;
    "EditProject(string,uint256,uint256,string)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "SaveProject(string,address,address,uint256,uint256,uint256,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ArbitrateProject"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuditProject"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChallengeProject"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EditProject"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SaveProject"): EventFragment;
}

export type ArbitrateProjectEvent = TypedEvent<
  [string, string, number] & {
    name: string;
    arbitrator: string;
    status: number;
  }
>;

export type AuditProjectEvent = TypedEvent<
  [string, string, BigNumber, string, number] & {
    name: string;
    auditor: string;
    auditPrice: BigNumber;
    comments: string;
    status: number;
  }
>;

export type ChallengeProjectEvent = TypedEvent<
  [string, string, BigNumber, string] & {
    name: string;
    challenger: string;
    challengePrice: BigNumber;
    comments: string;
  }
>;

export type EditProjectEvent = TypedEvent<
  [string, BigNumber, BigNumber, string] & {
    name: string;
    startTime: BigNumber;
    endTime: BigNumber;
    ipfsAddress: string;
  }
>;

export type RoleGrantedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type RoleRevokedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type SaveProjectEvent = TypedEvent<
  [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber
  ] & {
    name: string;
    owner: string;
    projectContract: string;
    startTime: BigNumber;
    endTime: BigNumber;
    projectPrice: BigNumber;
    ipfsAddress: string;
    projectId: BigNumber;
  }
>;

export class SafeMint extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SafeMintInterface;

  functions: {
    ARBITRATOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    AUDITOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    Arbitrate(
      name: string,
      status: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    adminSetAuditPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    adminSetChellengePrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    adminSetDuration(
      _duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    adminSetProjectPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    adminWithdraw(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    audit(
      name: string,
      comments: string,
      status: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    auditPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    auditRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string, BigNumber, number] & {
        projectId: BigNumber;
        auditor: string;
        auditTime: BigNumber;
        comments: string;
        auditFee: BigNumber;
        status: number;
      }
    >;

    challenge(
      name: string,
      comments: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    challengePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    challengeRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string, BigNumber] & {
        projectId: BigNumber;
        challenger: string;
        time: BigNumber;
        comments: string;
        challengeFee: BigNumber;
      }
    >;

    claimAuditReward(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimChellengeReward(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    contractAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    duration(overrides?: CallOverrides): Promise<[BigNumber]>;

    editProject(
      name: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    feeRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        auditTime: BigNumber;
        auditor: string;
        value: BigNumber;
      }
    >;

    getChallenge(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        })[]
      ]
    >;

    getLocked(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        })[]
      ]
    >;

    getPassed(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        })[]
      ]
    >;

    getPending(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        })[]
      ]
    >;

    getReject(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          string,
          string,
          BigNumber,
          string,
          BigNumber,
          BigNumber,
          string,
          BigNumber,
          number
        ] & {
          name: string;
          owner: string;
          createTime: BigNumber;
          projectContract: string;
          startTime: BigNumber;
          endTime: BigNumber;
          ipfsAddress: string;
          projectFee: BigNumber;
          status: number;
        })[]
      ]
    >;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRoleMemberIndex(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      }
    >;

    projectId(arg0: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

    projectName(name: string, overrides?: CallOverrides): Promise<[boolean]>;

    projectPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    saveProject(
      name: string,
      projectContract: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    user(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  ARBITRATOR_ROLE(overrides?: CallOverrides): Promise<string>;

  AUDITOR_ROLE(overrides?: CallOverrides): Promise<string>;

  Arbitrate(
    name: string,
    status: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  adminSetAuditPrice(
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  adminSetChellengePrice(
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  adminSetDuration(
    _duration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  adminSetProjectPrice(
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  adminWithdraw(
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  audit(
    name: string,
    comments: string,
    status: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  auditPrice(overrides?: CallOverrides): Promise<BigNumber>;

  auditRecord(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, string, BigNumber, number] & {
      projectId: BigNumber;
      auditor: string;
      auditTime: BigNumber;
      comments: string;
      auditFee: BigNumber;
      status: number;
    }
  >;

  challenge(
    name: string,
    comments: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  challengeArr(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  challengePrice(overrides?: CallOverrides): Promise<BigNumber>;

  challengeRecord(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, string, BigNumber] & {
      projectId: BigNumber;
      challenger: string;
      time: BigNumber;
      comments: string;
      challengeFee: BigNumber;
    }
  >;

  claimAuditReward(
    _projectId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimChellengeReward(
    _projectId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  contractAddress(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  duration(overrides?: CallOverrides): Promise<BigNumber>;

  editProject(
    name: string,
    startTime: BigNumberish,
    endTime: BigNumberish,
    ipfsAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  feeRecord(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber] & {
      auditTime: BigNumber;
      auditor: string;
      value: BigNumber;
    }
  >;

  getChallenge(
    start: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    })[]
  >;

  getLocked(
    start: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    })[]
  >;

  getPassed(
    start: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    })[]
  >;

  getPending(
    start: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    })[]
  >;

  getReject(
    start: BigNumberish,
    limit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    })[]
  >;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  getRoleMember(
    role: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleMemberCount(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRoleMemberIndex(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  lockedArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  passedArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  pendingArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  projectArr(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    }
  >;

  projectId(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  projectName(name: string, overrides?: CallOverrides): Promise<boolean>;

  projectPrice(overrides?: CallOverrides): Promise<BigNumber>;

  rejectArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  saveProject(
    name: string,
    projectContract: string,
    startTime: BigNumberish,
    endTime: BigNumberish,
    ipfsAddress: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  user(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    ARBITRATOR_ROLE(overrides?: CallOverrides): Promise<string>;

    AUDITOR_ROLE(overrides?: CallOverrides): Promise<string>;

    Arbitrate(
      name: string,
      status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    adminSetAuditPrice(
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    adminSetChellengePrice(
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    adminSetDuration(
      _duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    adminSetProjectPrice(
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    adminWithdraw(to: string, overrides?: CallOverrides): Promise<void>;

    audit(
      name: string,
      comments: string,
      status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    auditPrice(overrides?: CallOverrides): Promise<BigNumber>;

    auditRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string, BigNumber, number] & {
        projectId: BigNumber;
        auditor: string;
        auditTime: BigNumber;
        comments: string;
        auditFee: BigNumber;
        status: number;
      }
    >;

    challenge(
      name: string,
      comments: string,
      overrides?: CallOverrides
    ): Promise<void>;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    challengePrice(overrides?: CallOverrides): Promise<BigNumber>;

    challengeRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string, BigNumber] & {
        projectId: BigNumber;
        challenger: string;
        time: BigNumber;
        comments: string;
        challengeFee: BigNumber;
      }
    >;

    claimAuditReward(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimChellengeReward(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    contractAddress(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    duration(overrides?: CallOverrides): Promise<BigNumber>;

    editProject(
      name: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    feeRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        auditTime: BigNumber;
        auditor: string;
        value: BigNumber;
      }
    >;

    getChallenge(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      })[]
    >;

    getLocked(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      })[]
    >;

    getPassed(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      })[]
    >;

    getPending(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      })[]
    >;

    getReject(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      })[]
    >;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMemberIndex(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      }
    >;

    projectId(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    projectName(name: string, overrides?: CallOverrides): Promise<boolean>;

    projectPrice(overrides?: CallOverrides): Promise<BigNumber>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    saveProject(
      name: string,
      projectContract: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    user(arg0: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "ArbitrateProject(string,address,uint8)"(
      name?: string | null,
      arbitrator?: string | null,
      status?: null
    ): TypedEventFilter<
      [string, string, number],
      { name: string; arbitrator: string; status: number }
    >;

    ArbitrateProject(
      name?: string | null,
      arbitrator?: string | null,
      status?: null
    ): TypedEventFilter<
      [string, string, number],
      { name: string; arbitrator: string; status: number }
    >;

    "AuditProject(string,address,uint256,string,uint8)"(
      name?: string | null,
      auditor?: string | null,
      auditPrice?: null,
      comments?: null,
      status?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, number],
      {
        name: string;
        auditor: string;
        auditPrice: BigNumber;
        comments: string;
        status: number;
      }
    >;

    AuditProject(
      name?: string | null,
      auditor?: string | null,
      auditPrice?: null,
      comments?: null,
      status?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, number],
      {
        name: string;
        auditor: string;
        auditPrice: BigNumber;
        comments: string;
        status: number;
      }
    >;

    "ChallengeProject(string,address,uint256,string)"(
      name?: string | null,
      challenger?: string | null,
      challengePrice?: null,
      comments?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string],
      {
        name: string;
        challenger: string;
        challengePrice: BigNumber;
        comments: string;
      }
    >;

    ChallengeProject(
      name?: string | null,
      challenger?: string | null,
      challengePrice?: null,
      comments?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string],
      {
        name: string;
        challenger: string;
        challengePrice: BigNumber;
        comments: string;
      }
    >;

    "EditProject(string,uint256,uint256,string)"(
      name?: string | null,
      startTime?: null,
      endTime?: null,
      ipfsAddress?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, string],
      {
        name: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
      }
    >;

    EditProject(
      name?: string | null,
      startTime?: null,
      endTime?: null,
      ipfsAddress?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, string],
      {
        name: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
      }
    >;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "SaveProject(string,address,address,uint256,uint256,uint256,string,uint256)"(
      name?: string | null,
      owner?: string | null,
      projectContract?: string | null,
      startTime?: null,
      endTime?: null,
      projectPrice?: null,
      ipfsAddress?: null,
      projectId?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ],
      {
        name: string;
        owner: string;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        projectPrice: BigNumber;
        ipfsAddress: string;
        projectId: BigNumber;
      }
    >;

    SaveProject(
      name?: string | null,
      owner?: string | null,
      projectContract?: string | null,
      startTime?: null,
      endTime?: null,
      projectPrice?: null,
      ipfsAddress?: null,
      projectId?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ],
      {
        name: string;
        owner: string;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        projectPrice: BigNumber;
        ipfsAddress: string;
        projectId: BigNumber;
      }
    >;
  };

  estimateGas: {
    ARBITRATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    AUDITOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    Arbitrate(
      name: string,
      status: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    adminSetAuditPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    adminSetChellengePrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    adminSetDuration(
      _duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    adminSetProjectPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    adminWithdraw(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    audit(
      name: string,
      comments: string,
      status: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    auditPrice(overrides?: CallOverrides): Promise<BigNumber>;

    auditRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    challenge(
      name: string,
      comments: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    challengePrice(overrides?: CallOverrides): Promise<BigNumber>;

    challengeRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimAuditReward(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimChellengeReward(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    contractAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    duration(overrides?: CallOverrides): Promise<BigNumber>;

    editProject(
      name: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    feeRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChallenge(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLocked(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPassed(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPending(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReject(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMemberIndex(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectId(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    projectName(name: string, overrides?: CallOverrides): Promise<BigNumber>;

    projectPrice(overrides?: CallOverrides): Promise<BigNumber>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    saveProject(
      name: string,
      projectContract: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    user(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ARBITRATOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    AUDITOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    Arbitrate(
      name: string,
      status: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    adminSetAuditPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    adminSetChellengePrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    adminSetDuration(
      _duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    adminSetProjectPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    adminWithdraw(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    audit(
      name: string,
      comments: string,
      status: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    auditPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    auditRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    challenge(
      name: string,
      comments: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    challengePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    challengeRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimAuditReward(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimChellengeReward(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    contractAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    duration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    editProject(
      name: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    feeRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChallenge(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLocked(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPassed(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPending(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReject(
      start: BigNumberish,
      limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMemberIndex(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectName(
      name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    saveProject(
      name: string,
      projectContract: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      ipfsAddress: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    user(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
