/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SafeMintDataInterface extends ethers.utils.Interface {
  functions: {
    "ARBITRATOR_ROLE()": FunctionFragment;
    "AUDITOR_ROLE()": FunctionFragment;
    "auditPrice()": FunctionFragment;
    "auditRecord(uint256,uint256)": FunctionFragment;
    "challengeArr(uint256)": FunctionFragment;
    "challengePrice()": FunctionFragment;
    "challengeRecord(uint256,uint256)": FunctionFragment;
    "contractAddress(address)": FunctionFragment;
    "duration()": FunctionFragment;
    "feeRecord(uint256)": FunctionFragment;
    "lockedArr(uint256)": FunctionFragment;
    "passedArr(uint256)": FunctionFragment;
    "pendingArr(uint256)": FunctionFragment;
    "projectArr(uint256)": FunctionFragment;
    "projectId(bytes32)": FunctionFragment;
    "projectPrice()": FunctionFragment;
    "rejectArr(uint256)": FunctionFragment;
    "user(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ARBITRATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auditPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auditRecord",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challengePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challengeRecord",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "duration", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "passedArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projectPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rejectArr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "user", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "ARBITRATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auditPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "auditRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeArr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "duration", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockedArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "passedArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "projectArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "projectId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rejectArr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "user", data: BytesLike): Result;

  events: {
    "ArbitrateProject(string,address,uint8)": EventFragment;
    "AuditProject(string,address,uint256,string,uint8)": EventFragment;
    "ChallengeProject(string,address,uint256,string)": EventFragment;
    "EditProject(string,uint256,uint256,string)": EventFragment;
    "SaveProject(string,address,address,uint256,uint256,uint256,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ArbitrateProject"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuditProject"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChallengeProject"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EditProject"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SaveProject"): EventFragment;
}

export type ArbitrateProjectEvent = TypedEvent<
  [string, string, number] & {
    name: string;
    arbitrator: string;
    status: number;
  }
>;

export type AuditProjectEvent = TypedEvent<
  [string, string, BigNumber, string, number] & {
    name: string;
    auditor: string;
    auditPrice: BigNumber;
    comments: string;
    status: number;
  }
>;

export type ChallengeProjectEvent = TypedEvent<
  [string, string, BigNumber, string] & {
    name: string;
    challenger: string;
    challengePrice: BigNumber;
    comments: string;
  }
>;

export type EditProjectEvent = TypedEvent<
  [string, BigNumber, BigNumber, string] & {
    name: string;
    startTime: BigNumber;
    endTime: BigNumber;
    ipfsAddress: string;
  }
>;

export type SaveProjectEvent = TypedEvent<
  [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber
  ] & {
    name: string;
    owner: string;
    projectContract: string;
    startTime: BigNumber;
    endTime: BigNumber;
    projectPrice: BigNumber;
    ipfsAddress: string;
    projectId: BigNumber;
  }
>;

export class SafeMintData extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SafeMintDataInterface;

  functions: {
    ARBITRATOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    AUDITOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    auditPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    auditRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string, BigNumber, number] & {
        projectId: BigNumber;
        auditor: string;
        auditTime: BigNumber;
        comments: string;
        auditFee: BigNumber;
        status: number;
      }
    >;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    challengePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    challengeRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string, BigNumber] & {
        projectId: BigNumber;
        challenger: string;
        time: BigNumber;
        comments: string;
        challengeFee: BigNumber;
      }
    >;

    contractAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    duration(overrides?: CallOverrides): Promise<[BigNumber]>;

    feeRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        auditTime: BigNumber;
        auditor: string;
        value: BigNumber;
      }
    >;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      }
    >;

    projectId(arg0: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

    projectPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    user(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  ARBITRATOR_ROLE(overrides?: CallOverrides): Promise<string>;

  AUDITOR_ROLE(overrides?: CallOverrides): Promise<string>;

  auditPrice(overrides?: CallOverrides): Promise<BigNumber>;

  auditRecord(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, string, BigNumber, number] & {
      projectId: BigNumber;
      auditor: string;
      auditTime: BigNumber;
      comments: string;
      auditFee: BigNumber;
      status: number;
    }
  >;

  challengeArr(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  challengePrice(overrides?: CallOverrides): Promise<BigNumber>;

  challengeRecord(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, string, BigNumber] & {
      projectId: BigNumber;
      challenger: string;
      time: BigNumber;
      comments: string;
      challengeFee: BigNumber;
    }
  >;

  contractAddress(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  duration(overrides?: CallOverrides): Promise<BigNumber>;

  feeRecord(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber] & {
      auditTime: BigNumber;
      auditor: string;
      value: BigNumber;
    }
  >;

  lockedArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  passedArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  pendingArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  projectArr(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      number
    ] & {
      name: string;
      owner: string;
      createTime: BigNumber;
      projectContract: string;
      startTime: BigNumber;
      endTime: BigNumber;
      ipfsAddress: string;
      projectFee: BigNumber;
      status: number;
    }
  >;

  projectId(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  projectPrice(overrides?: CallOverrides): Promise<BigNumber>;

  rejectArr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  user(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    ARBITRATOR_ROLE(overrides?: CallOverrides): Promise<string>;

    AUDITOR_ROLE(overrides?: CallOverrides): Promise<string>;

    auditPrice(overrides?: CallOverrides): Promise<BigNumber>;

    auditRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string, BigNumber, number] & {
        projectId: BigNumber;
        auditor: string;
        auditTime: BigNumber;
        comments: string;
        auditFee: BigNumber;
        status: number;
      }
    >;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    challengePrice(overrides?: CallOverrides): Promise<BigNumber>;

    challengeRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, string, BigNumber] & {
        projectId: BigNumber;
        challenger: string;
        time: BigNumber;
        comments: string;
        challengeFee: BigNumber;
      }
    >;

    contractAddress(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    duration(overrides?: CallOverrides): Promise<BigNumber>;

    feeRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        auditTime: BigNumber;
        auditor: string;
        value: BigNumber;
      }
    >;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        number
      ] & {
        name: string;
        owner: string;
        createTime: BigNumber;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
        projectFee: BigNumber;
        status: number;
      }
    >;

    projectId(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    projectPrice(overrides?: CallOverrides): Promise<BigNumber>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    user(arg0: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "ArbitrateProject(string,address,uint8)"(
      name?: string | null,
      arbitrator?: string | null,
      status?: null
    ): TypedEventFilter<
      [string, string, number],
      { name: string; arbitrator: string; status: number }
    >;

    ArbitrateProject(
      name?: string | null,
      arbitrator?: string | null,
      status?: null
    ): TypedEventFilter<
      [string, string, number],
      { name: string; arbitrator: string; status: number }
    >;

    "AuditProject(string,address,uint256,string,uint8)"(
      name?: string | null,
      auditor?: string | null,
      auditPrice?: null,
      comments?: null,
      status?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, number],
      {
        name: string;
        auditor: string;
        auditPrice: BigNumber;
        comments: string;
        status: number;
      }
    >;

    AuditProject(
      name?: string | null,
      auditor?: string | null,
      auditPrice?: null,
      comments?: null,
      status?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, number],
      {
        name: string;
        auditor: string;
        auditPrice: BigNumber;
        comments: string;
        status: number;
      }
    >;

    "ChallengeProject(string,address,uint256,string)"(
      name?: string | null,
      challenger?: string | null,
      challengePrice?: null,
      comments?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string],
      {
        name: string;
        challenger: string;
        challengePrice: BigNumber;
        comments: string;
      }
    >;

    ChallengeProject(
      name?: string | null,
      challenger?: string | null,
      challengePrice?: null,
      comments?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string],
      {
        name: string;
        challenger: string;
        challengePrice: BigNumber;
        comments: string;
      }
    >;

    "EditProject(string,uint256,uint256,string)"(
      name?: string | null,
      startTime?: null,
      endTime?: null,
      ipfsAddress?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, string],
      {
        name: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
      }
    >;

    EditProject(
      name?: string | null,
      startTime?: null,
      endTime?: null,
      ipfsAddress?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, string],
      {
        name: string;
        startTime: BigNumber;
        endTime: BigNumber;
        ipfsAddress: string;
      }
    >;

    "SaveProject(string,address,address,uint256,uint256,uint256,string,uint256)"(
      name?: string | null,
      owner?: string | null,
      projectContract?: string | null,
      startTime?: null,
      endTime?: null,
      projectPrice?: null,
      ipfsAddress?: null,
      projectId?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ],
      {
        name: string;
        owner: string;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        projectPrice: BigNumber;
        ipfsAddress: string;
        projectId: BigNumber;
      }
    >;

    SaveProject(
      name?: string | null,
      owner?: string | null,
      projectContract?: string | null,
      startTime?: null,
      endTime?: null,
      projectPrice?: null,
      ipfsAddress?: null,
      projectId?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ],
      {
        name: string;
        owner: string;
        projectContract: string;
        startTime: BigNumber;
        endTime: BigNumber;
        projectPrice: BigNumber;
        ipfsAddress: string;
        projectId: BigNumber;
      }
    >;
  };

  estimateGas: {
    ARBITRATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    AUDITOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    auditPrice(overrides?: CallOverrides): Promise<BigNumber>;

    auditRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    challengePrice(overrides?: CallOverrides): Promise<BigNumber>;

    challengeRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    duration(overrides?: CallOverrides): Promise<BigNumber>;

    feeRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectId(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    projectPrice(overrides?: CallOverrides): Promise<BigNumber>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    user(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ARBITRATOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    AUDITOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    auditPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    auditRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    challengeArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    challengePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    challengeRecord(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    duration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeRecord(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    passedArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rejectArr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    user(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
